### ISSUE TITLE
git lfs error

### ISSUE THREAD

**Issue by liuyifang** [ManchesterBioinference/GrandPrix#1]
Hi, I would like to try your method, but meet this error:

> $ git clone https://github.com/ManchesterBioinference/GrandPrix
Cloning into 'GrandPrix'...
remote: Enumerating objects: 528, done.
remote: Total 528 (delta 0), reused 0 (delta 0), pack-reused 528
Receiving objects: 100% (528/528), 10.33 MiB | 29.00 KiB/s, done.
Resolving deltas: 100% (239/239), done.
Downloading data/Windram/DeLorean_samples/Matern32/WindreamDeLoreanBestSampleMCMC_Matern32.csv (2.6 KB)
Error downloading object: data/Windram/DeLorean_samples/Matern32/WindreamDeLoreanBestSampleMCMC_Matern32.csv (809b560): Smudge error: Error downloading data/Windram/DeLorean_samples/Matern32/WindreamDeLoreanBestSampleMCMC_Matern32.csv (809b5600bad8bfcb761ab72a8fd5565d8e6ef4a19d5ef303b602e387d6d74e9f): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Yifang

**Comment by magnusrattray** [comment]
Hi,

Sorry about that - I think I've sorted out this issue now, please try again.

Magnus.

**Comment by liuyifang** [comment]
Hi, Magnus

Thank you for your quick reply. I have successfully cloned your GrandPrix now. And here is the clone information:

> git clone https://github.com/ManchesterBioinference/GrandPr 
Cloning into 'GrandPrix'...
remote: Enumerating objects: 528, done.
remote: Total 528 (delta 0), reused 0 (delta 0), pack-reused 528
Receiving objects: 100% (528/528), 10.33 MiB | 461.00 KiB/s, done.
Resolving deltas: 100% (239/239), done.
Filtering content: 100% (21/21), 1.36 GiB | 932.00 KiB/s, done.
Encountered 7 file(s) that should have been pointers, but weren't:
	data/Guo/GuoTrainingData.csv
	data/McDavid/McDavidCellMeta.csv
	data/McDavid/McDavid_gene.csv
	data/McDavid/McDavidtrainingData.csv
	data/Shalek/ShalekCellMeta.csv
	data/Shalek/ShalekComparison.csv
	data/Shalek/ShalekTrainingData.csv
